# coding=UTF-8

from runnable import *

alchemical = choice('Item alquímico',
                    [(12, value('Fogo alquímico, frascos', 'd(1,4)')),
                     (24, value('Ácido, frascos', 'd(2,4)')),
                     (36, value('Bastões de fumaça, quantidade', 'd(1,4)')),
                     (48, value('Água benta, frascos', 'd(1,4)')),
                     (68, value('Antídoto, doses', 'd(1,4)')),
                     (74, 'Tocha da chama eterna'),
                     (88, value('Bolsas de cola, quantidade', 'd(1,4)')),
                     (100, value('Pedras trovão, quantidade', 'd(1,4)'))])

armor = sized(choice('Armadura',
                     [(12, 'Camisão de cota de malha'),
                      (18, 'Corselete de couro batido obra-prima'),
                      (26, 'Peitoral de aço'),
                      (34, 'Loriga segmentada'),
                      (54, 'Meia armadura'),
                      (80, 'Armadura de batalha'),
                      (90, choice('Escudo de madeira negra',
                                  [(50, 'Broquel'),
                                   (100, 'Escudo grande')])),
                      (100, choice('Escudo obra-prima',
                                   [(17, 'Broquel'),
                                    (40, 'Escudo pequeno de madeira'),
                                    (60, 'Escudo pequeno de metal'),
                                    (83, 'Escudo grande de madeira'),
                                    (100, 'Escudo grande de metal')]))]))

common_meelee = choice('Comum corpo a corpo',
                       [(4, sized('Adaga')),
                        (14, sized('Machado grande')),
                        (24, sized('Espada larga')),
                        (28, sized('Kama')),
                        (41, sized('Espada longa')),
                        (45, sized('Maça leve')),
                        (50, sized('Maça pesada')),
                        (54, sized('Nunchaku')),
                        (57, sized('Bordão')),
                        (61, sized('Sabre')),
                        (66, sized('Cimitarra')),
                        (70, sized('Lança curta')),
                        (74, sized('Sianghan')),
                        (84, sized('Espada bastarda')),
                        (89, sized('Espada curta')),
                        (100, 'Machado de combate anão')])

common_distance = choice('Comum a distância',
                         [(10, choice('Munição',
                                      [(50, 'Flechas (50)'),
                                       (80, 'Virotes de besta (50)'),
                                       (100, 'Balas de funda (50)')])),
                          (15, sized('Machado de arremesso')),
                          (25, sized('Besta pesada')),
                          (35, sized('Besta leve')),
                          (39, sized('Dardo')),
                          (41, sized('Azagaia')),
                          (46, sized('Arco curto')),
                          (51, sized('Arco curto composto')),
                          (56, sized('Arco curto composto reforçado +1')),
                          (61, sized('Arco curto composto reforçado +2')),
                          (65, sized('Funda')),
                          (75, sized('Arco longo')),
                          (80, sized('Arco longo composto')),
                          (85, sized('Arco longo composto reforçado +1')),
                          (90, sized('Arco longo composto reforçado +2')),
                          (95, sized('Arco longo composto reforçado +3')),
                          (100, sized('Arco longo composto reforçado +4'))])

uncommon = choice('Incomum',
                  [(3, 'Machado orc duplo'),
                   (7, sized('Machado de combate')),
                   (10, sized('Corrente com cravos')),
                   (12, sized('Clava')),
                   (16, sized('Besta de mão')),
                   (19, sized('Besta de repetição')),
                   (21, sized('Adaga de soco')),
                   (23, sized('Falcione')),
                   (26, sized('Mangual atroz')),
                   (31, sized('Mangual pesado')),
                   (35, sized('Mangual leve')),
                   (37, sized('Manopla')),
                   (39, sized('Manopla com cravos')),
                   (41, sized('Glaive')),
                   (43, sized('Clava grande')),
                   (45, sized('Guisarme')),
                   (48, sized('Alabarda')),
                   (51, sized('Meia lança')),
                   (54, 'Martelo gnomo com gancho'),
                   (56, sized('Martelo leve')),
                   (58, sized('Machadinha')),
                   (61, sized('Kukri')),
                   (64, sized('Lança montada')),
                   (67, sized('Lança longa')),
                   (70, sized('Maça estrela')),
                   (72, sized('Rede')),
                   (74, sized('Picareta pesada')),
                   (76, sized('Picareta leve')),
                   (78, sized('Ranseur')),
                   (80, sized('Porrete')),
                   (82, sized('Foice longa')),
                   (84, sized('Shuriken')),
                   (86, sized('Foice curta')),
                   (89, sized('Espada dupla')),
                   (91, sized('Tridente')),
                   (94, 'Urgrosh anão'),
                   (97, sized('Martelo de guerra')),
                   (100, sized('Chicote'))])

weapons = choice('Arma',
                 [(50, common_meelee),
                  (70, uncommon),
                  (100, common_distance)])

equipment = choice('Ferramentas e Equipamento',
                   [(3, sized('Mochila vazia')),
                    (6, sized('Pé-de-cabra')),
                    (11, 'Lanterna furta-fogo'),
                    (16, 'Tranca simples'),
                    (21, 'Tranca média'),
                    (28, 'Tranca boa'),
                    (35, 'Tranca excelente'),
                    (40, sized('Algemas obra-prima')),
                    (43, 'Espelho pequeno de metal'),
                    (46, 'Corda de seda (15 m)'),
                    (53, 'Luneta'),
                    (58, sized('Ferramentas de artesão, obra-prima')),
                    (63, 'Kit de escalada'),
                    (68, 'Kit de disfarce'),
                    (73, 'Kit de primeiros socorros'),
                    (77, 'Símbolo sagrado, prata'), # TODO: especificar
                    (81, 'Ampulheta'),
                    (88, 'Lente de aumento'),
                    (95, sized('Instrumento musical, obra-prima')), # TODO: especificar
                    (100, sized('Instrumentos de ladrão, obra-prima'))])

mundane = choice('Item mundano',
                 [(17, alchemical),
                  (50, armor),
                  (83, weapons),
                  (100, equipment)])
